language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    composer global require --no-interaction --prefer-dist scrutinizer/ocular
    ~/.config/composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
